CREATE TABLE STUDENTS (
	STUID INT,
	FIRSTNAME VARCHAR(25),
	LASTNAME VARCHAR(25),
	WEBSITE VARCHAR(50),
	CITY VARCHAR(25),
	DIVISION VARCHAR(20)
)

SELECT * FROM STUDENTS

INSERT INTO STUDENTS VALUES
(
	1011, 'KEYUR', 'PATEL', 'TECHONTHENET.COM' , 'RAJKOT', 'II-BCX'
)

INSERT INTO STUDENTS VALUES
(
	1022, 'HARDIK','SHAH' , 'DIGMINECRAFT.COM' ,'AHMEDABAD' , 'I-BCY'
)

INSERT INTO STUDENTS VALUES
(
	1033, 'KAJAL','TRIVEDI' , 'BIGACTIVITIES.COM' ,'BARODA' , 'IV-DCX'
)

INSERT INTO STUDENTS VALUES
(
	1044, 'BHOOMI','GAJERA' , 'CHECKYOURMATH.COM' ,'AHMEDABAD' , 'III-DCW'
)

INSERT INTO STUDENTS VALUES
(
	1055, 'HARMIT','MITEL' , 'NULL' ,'RAJKOT' , 'II-BCY'
)

INSERT INTO STUDENTS VALUES
(
	1066, 'ASHOK','JANI' , 'NULL' ,'BARODA' , 'II-BCZ'
)


SELECT FIRSTNAME FROM STUDENTS WHERE FIRSTNAME LIKE 'K%' 
SELECT FIRSTNAME FROM STUDENTS WHERE FIRSTNAME LIKE '_____'
SELECT FIRSTNAME, LASTNAME FROM STUDENTS WHERE CITY LIKE '_____A'
SELECT LASTNAME FROM STUDENTS WHERE LASTNAME LIKE'%TEL'
SELECT FIRSTNAME FROM STUDENTS WHERE FIRSTNAME LIKE 'HA%T'
SELECT FIRSTNAME FROM STUDENTS WHERE FIRSTNAME LIKE 'K_Y%'
SELECT WEBSITE FROM STUDENTS WHERE WEBSITE IS NULL AND FIRSTNAME LIKE '_____'
SELECT LASTNAME FROM STUDENTS WHERE LASTNAME LIKE '%JER%'
SELECT CITY FROM STUDENTS WHERE CITY LIKE '[R,B]%'
SELECT WEBSITE FROM STUDENTS WHERE WEBSITE IS NOT NULL  
SELECT  FIRSTNAME FROM STUDENTS WHERE FIRSTNAME LIKE '[A-H]%'

